import HTML from '../web/index.html';
import CSS from '../web/style.css';
import APP from '../web/app.browser.js';
import CRYPTO from '../web/crypto.browser.js';
import ICON from '../web/favicon.svg';
import FONT from '../web/fonts/dm-sans.woff2';

const MAX_BODY = 96 * 1024;
const MAX_CIPHERTEXT = 65536 + 16;
const ID = /^[a-f0-9]{32}$/;
const TTL = new Set([3600, 86400, 604800, 2592000]);
const HEADERS = {
  'Cache-Control': 'no-store',
  'Content-Security-Policy': "default-src 'none'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; require-trusted-types-for 'script'; trusted-types 'none'",
  'Referrer-Policy': 'no-referrer',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Strict-Transport-Security': 'max-age=31536000',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), display-capture=(), payment=(), usb=(), browsing-topics=(), clipboard-read=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  'Cross-Origin-Embedder-Policy': 'require-corp',
  'X-Robots-Tag': 'noindex, nofollow',
};

type Envelope = { version: 2; iv: string; data: string };
type Paste = {
  encrypted_data: string;
  created: number;
  expires_at: number;
  burn_after_read: number;
  has_password: number;
};

class HttpError extends Error {
  constructor(public status: number, message: string) { super(message); }
}

function response(body: BodyInit | null, status = 200, headers: HeadersInit = {}) {
  return new Response(body, { status, headers: { ...HEADERS, ...headers } });
}

function json(body: unknown, status = 200, headers: Record<string, string> = {}) {
  return response(JSON.stringify(body), status, { 'Content-Type': 'application/json; charset=utf-8', ...headers });
}

function object(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function base64Bytes(value: unknown, min: number, max: number): value is string {
  if (typeof value !== 'string' || value.length > Math.ceil(max * 4 / 3) || !/^[A-Za-z0-9_-]+$/.test(value)) return false;
  try {
    const raw = atob(value.replace(/-/g, '+').replace(/_/g, '/'));
    return raw.length >= min && raw.length <= max && btoa(raw).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '') === value;
  } catch { return false; }
}

async function readBody(request: Request, maxBytes = MAX_BODY): Promise<unknown> {
  if (request.headers.get('content-type')?.split(';')[0].trim().toLowerCase() !== 'application/json') {
    throw new HttpError(415, 'Use application/json');
  }
  if (Number(request.headers.get('content-length')) > maxBytes) throw new HttpError(413, 'Request too large');
  if (!request.body) throw new HttpError(400, 'Missing JSON body');
  const reader = request.body.getReader();
  const chunks: Uint8Array[] = [];
  let length = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      length += value.byteLength;
      if (length > maxBytes) {
        await reader.cancel();
        throw new HttpError(413, 'Request too large');
      }
      chunks.push(value);
    }
  } finally { reader.releaseLock(); }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.length; }
  try { return JSON.parse(new TextDecoder('utf-8', { fatal: true, ignoreBOM: false }).decode(bytes)); }
  catch { throw new HttpError(400, 'Invalid JSON'); }
}

async function create(request: Request, env: Env) {
  const body = await readBody(request);
  if (!object(body)) throw new HttpError(400, 'Invalid request');
  const { encryptedData, expiresIn, burnAfterRead, hasPassword, readTokenHash } = body;
  if (!object(encryptedData) || encryptedData.version !== 2 ||
      !base64Bytes(encryptedData.iv, 12, 12) || !base64Bytes(encryptedData.data, 17, MAX_CIPHERTEXT)) {
    throw new HttpError(400, 'Invalid encrypted data');
  }
  if (typeof expiresIn !== 'number' || !TTL.has(expiresIn)) throw new HttpError(400, 'Invalid expiration');
  if (typeof burnAfterRead !== 'boolean' || typeof hasPassword !== 'boolean') throw new HttpError(400, 'Invalid options');
  if (!base64Bytes(readTokenHash, 32, 32)) throw new HttpError(400, 'A read token is required. Refresh the page and try again.');
  // IDs are generated by the server: a caller can never overwrite an existing paste.
  const id = crypto.randomUUID().replaceAll('-', '');
  const created = Date.now();
  const expiresAt = created + expiresIn * 1000;
  const envelope: Envelope = { version: 2, iv: encryptedData.iv, data: encryptedData.data };
  await env.DB.prepare('INSERT INTO pastes (id, encrypted_data, created, expires_at, burn_after_read, has_password, read_token_hash) VALUES (?, ?, ?, ?, ?, ?, ?)')
    .bind(id, JSON.stringify(envelope), created, expiresAt, Number(burnAfterRead), Number(hasPassword), readTokenHash).run();
  return json({ id, expiresAt }, 201);
}

async function read(request: Request, id: string, env: Env) {
  const body = await readBody(request, 1024);
  if (!object(body)) throw new HttpError(400, 'Invalid request');
  let tokenHash: string | null = null;
  if (body.readToken !== undefined) {
    if (!base64Bytes(body.readToken, 32, 32)) throw new HttpError(400, 'Invalid read token');
    const token = Uint8Array.from(atob(body.readToken.replace(/-/g, '+').replace(/_/g, '/')), char => char.charCodeAt(0));
    const hash = new Uint8Array(await crypto.subtle.digest('SHA-256', token));
    tokenHash = btoa(String.fromCharCode(...hash)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  }
  const now = Date.now();
  // DELETE ... RETURNING is one atomic statement. Concurrent requests cannot both
  // receive a one-time paste. Authorization is part of that same statement.
  // NULL hashes belong only to existing v2 rows; new creates require a hash.
  const burned = await env.DB.prepare('DELETE FROM pastes WHERE id = ? AND read_token_hash IS ? AND burn_after_read = 1 AND expires_at > ? RETURNING encrypted_data, created, expires_at, burn_after_read, has_password')
    .bind(id, tokenHash, now).first<Paste>();
  const paste = burned ?? await env.DB.prepare('SELECT encrypted_data, created, expires_at, burn_after_read, has_password FROM pastes WHERE id = ? AND read_token_hash IS ? AND burn_after_read = 0 AND expires_at > ?')
    .bind(id, tokenHash, now).first<Paste>();
  if (!paste) return json({ error: 'Message not found, expired, or already opened' }, 404);
  return json({ data: JSON.parse(paste.encrypted_data), created: paste.created, expiresAt: paste.expires_at,
    burnAfterRead: Boolean(paste.burn_after_read), hasPassword: Boolean(paste.has_password) });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.protocol === 'http:' && !['localhost', '127.0.0.1', '[::1]'].includes(url.hostname)) {
      url.protocol = 'https:';
      return response(null, 308, { Location: url.href });
    }
    try {
      if (url.pathname.startsWith('/api/')) {
        const match = /^\/api\/read\/([a-f0-9]{32})$/.exec(url.pathname);
        if (url.pathname !== '/api/create' && !match) return json({ error: 'Not found' }, 404);
        if (request.method !== 'POST') return json({ error: 'Use POST' }, 405, { Allow: 'POST' });
        const origin = request.headers.get('origin');
        if ((origin && origin !== url.origin) || request.headers.get('sec-fetch-site') === 'cross-site') {
          return json({ error: 'Cross-origin requests are not allowed' }, 403);
        }
        if (request.headers.get('content-type')?.split(';')[0].trim().toLowerCase() !== 'application/json') {
          return json({ error: 'Use application/json' }, 415);
        }
        const limiter = match ? env.READ_LIMITER : env.CREATE_LIMITER;
        const { success } = await limiter.limit({ key: request.headers.get('CF-Connecting-IP') ?? 'local' });
        if (!success) return json({ error: 'Too many requests. Try again in a minute.' }, 429, { 'Retry-After': '60' });
        if (match && ID.test(match[1])) return await read(request, match[1], env);
        return await create(request, env);
      }
      if (request.method !== 'GET' && request.method !== 'HEAD') return response('Method not allowed', 405, { Allow: 'GET, HEAD' });
      const assets: Record<string, [BodyInit, string]> = {
        '/': [HTML, 'text/html; charset=utf-8'],
        '/index.html': [HTML, 'text/html; charset=utf-8'],
        '/style.css': [CSS, 'text/css; charset=utf-8'],
        '/font.woff2': [FONT, 'font/woff2'],
        '/app.js': [APP, 'text/javascript; charset=utf-8'],
        '/crypto.js': [CRYPTO, 'text/javascript; charset=utf-8'],
        '/favicon.svg': [ICON, 'image/svg+xml'],
        '/favicon.ico': [ICON, 'image/svg+xml'],
      };
      const asset = assets[url.pathname];
      return asset ? response(request.method === 'HEAD' ? null : asset[0], 200, { 'Content-Type': asset[1] }) : response('Not found', 404);
    } catch (error) {
      if (error instanceof HttpError) return json({ error: error.message }, error.status);
      // Do not log request URLs, payloads, keys, or raw database exceptions.
      console.error(JSON.stringify({ event: 'request_failed' }));
      return json({ error: 'Service temporarily unavailable' }, 503);
    }
  },
  async scheduled(_event, env) {
    // Expiration is enforced at read time; this removes inaccessible rows in batches.
    await env.DB.prepare('DELETE FROM pastes WHERE id IN (SELECT id FROM pastes WHERE expires_at <= ? LIMIT 1000)')
      .bind(Date.now()).run();
  },
} satisfies ExportedHandler<Env>;
